import prisma from "@/lib/db";

async function main() {
  // Create or find a user
  const user = await prisma.user.findFirst({
    include: {
      emailAddresses: true,
    },
  });
  if (!user) {
    return;
  }

  console.log("Found user:", user.email);

  if (user.emailAddresses.length === 0) {
    console.log("No email addresses found for user");
    return;
  }

  const firstEmailAddress = user.emailAddresses[0];
  console.log("Creating emails for:", firstEmailAddress.email);

  // Create 20 emails for the first email address
  await prisma.emails.createMany({
    data: [
      {
        id: "email_1",
        messageId: "msg_001",
        from: "support@example.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Welcome to AsManyMail!",
        text: "Welcome to AsManyMail! We're excited to have you on board.",
        html: "<h1>Welcome to AsManyMail!</h1><p>We're excited to have you on board.</p>",
        date: new Date("2026-01-15T10:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_2",
        messageId: "msg_002",
        from: "billing@company.com",
        to: [firstEmailAddress.email],
        cc: ["accounting@company.com"],
        bcc: [],
        subject: "Invoice for January 2026",
        text: "Please find attached your invoice for January 2026.",
        html: "<h2>Invoice for January 2026</h2><p>Please find attached your invoice.</p>",
        date: new Date("2026-01-20T14:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_3",
        messageId: "msg_003",
        from: "newsletter@techblog.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Weekly Tech Digest - AI Advances",
        text: "This week's highlights: New AI models and quantum computing breakthroughs.",
        html: "<h1>Weekly Tech Digest</h1><p>This week's highlights in technology.</p>",
        date: new Date("2026-01-22T08:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_4",
        messageId: "msg_004",
        from: "manager@workplace.com",
        to: [firstEmailAddress.email],
        cc: ["team@workplace.com"],
        bcc: [],
        subject: "Project Update - Q1 Goals",
        text: "Team, here's an update on our Q1 goals. We're making great progress!",
        html: "<h2>Project Update - Q1 Goals</h2><p>Great progress on our goals!</p>",
        date: new Date("2026-01-25T11:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_5",
        messageId: "msg_005",
        from: "noreply@github.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Pull Request: Feature Implementation",
        text: "A new pull request has been opened on your repository.",
        html: "<h3>New Pull Request</h3><p>Review the new feature implementation.</p>",
        date: new Date("2026-01-28T16:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_6",
        messageId: "msg_006",
        from: "security@company.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Security Alert: New Login Detected",
        text: "A new login was detected from an unrecognized device.",
        html: "<h2>Security Alert</h2><p>New login from unrecognized device.</p>",
        date: new Date("2026-02-01T09:20:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_7",
        messageId: "msg_007",
        from: "hr@company.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Time Off Request Approved",
        text: "Your time off request for February 15-17 has been approved.",
        html: "<h2>Time Off Approved</h2><p>Your request has been approved.</p>",
        date: new Date("2026-02-02T13:10:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_8",
        messageId: "msg_008",
        from: "updates@linkedin.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Weekly Job Matches",
        text: "Check out these job opportunities that match your profile.",
        html: "<h1>Weekly Job Matches</h1><p>New opportunities for you.</p>",
        date: new Date("2026-02-03T07:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_9",
        messageId: "msg_009",
        from: "notifications@slack.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "You have 15 unread messages",
        text: "You have unread messages in your Slack workspace.",
        html: "<h3>Unread Messages</h3><p>15 messages waiting for you.</p>",
        date: new Date("2026-02-03T18:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_10",
        messageId: "msg_010",
        from: "calendar@google.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Event Reminder: Team Standup",
        text: "Reminder: Team Standup starts in 1 hour.",
        html: "<h2>Event Reminder</h2><p>Team Standup in 1 hour.</p>",
        date: new Date("2026-02-04T08:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_11",
        messageId: "msg_011",
        from: "orders@amazon.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Order Has Been Shipped",
        text: "Your order #12345 has been shipped and will arrive in 2-3 days.",
        html: "<h2>Order Shipped</h2><p>Track your package delivery.</p>",
        date: new Date("2026-02-04T14:25:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_12",
        messageId: "msg_012",
        from: "marketing@startup.io",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Exclusive Offer: 50% Off Premium Plan",
        text: "Limited time offer: Get 50% off our premium plan for 3 months.",
        html: "<h1>Exclusive Offer</h1><p>50% off premium for 3 months!</p>",
        date: new Date("2026-02-05T10:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_13",
        messageId: "msg_013",
        from: "notifications@twitter.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Tweet Got 100 Likes!",
        text: "Your recent tweet has received 100 likes and 25 retweets.",
        html: "<h3>Tweet Performance</h3><p>100 likes and 25 retweets!</p>",
        date: new Date("2026-02-05T15:40:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_14",
        messageId: "msg_014",
        from: "finance@bank.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Monthly Statement Available",
        text: "Your monthly statement for January 2026 is now available.",
        html: "<h2>Monthly Statement</h2><p>View your January statement.</p>",
        date: new Date("2026-02-06T06:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_15",
        messageId: "msg_015",
        from: "events@meetup.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Event: Web Development Workshop",
        text: "Join us for a web development workshop this Saturday.",
        html: "<h1>New Event</h1><p>Web Development Workshop this Saturday.</p>",
        date: new Date("2026-02-06T12:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_16",
        messageId: "msg_016",
        from: "support@hosting.com",
        to: [firstEmailAddress.email],
        cc: ["billing@hosting.com"],
        bcc: [],
        subject: "Server Maintenance Scheduled",
        text: "Scheduled maintenance on your server will occur on Feb 10th.",
        html: "<h2>Server Maintenance</h2><p>Scheduled for Feb 10th, 2-4 AM.</p>",
        date: new Date("2026-02-06T17:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_17",
        messageId: "msg_017",
        from: "digest@medium.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Top Stories For You",
        text: "Here are today's top stories curated for your interests.",
        html: "<h1>Top Stories</h1><p>Curated content just for you.</p>",
        date: new Date("2026-02-07T05:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_18",
        messageId: "msg_018",
        from: "alerts@stackoverflow.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Answer to Your Question",
        text: "Someone has answered your question about React hooks.",
        html: "<h3>New Answer</h3><p>Check out the answer to your React question.</p>",
        date: new Date("2026-02-07T08:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_19",
        messageId: "msg_019",
        from: "team@figma.com",
        to: [firstEmailAddress.email],
        cc: ["design@company.com"],
        bcc: [],
        subject: "Design Review: Mobile App UI",
        text: "Your team has shared a new design for review.",
        html: "<h2>Design Review</h2><p>New mobile app UI design shared.</p>",
        date: new Date("2026-02-07T11:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_20",
        messageId: "msg_020",
        from: "donotreply@paypal.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Payment Received: $500.00",
        text: "You have received a payment of $500.00 from Client XYZ.",
        html: "<h2>Payment Received</h2><p>$500.00 from Client XYZ.</p>",
        date: new Date("2026-02-07T14:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_21",
        messageId: "msg_021",
        from: "notifications@dropbox.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "File Shared: Q4 Report.pdf",
        text: "John Doe has shared 'Q4 Report.pdf' with you on Dropbox.",
        html: "<h2>File Shared</h2><p>John Doe shared Q4 Report.pdf with you.</p>",
        date: new Date("2026-01-16T09:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_22",
        messageId: "msg_022",
        from: "alerts@jira.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Issue Updated: PROJ-456",
        text: "The issue PROJ-456 has been updated with new comments.",
        html: "<h3>Issue Updated</h3><p>Check the latest updates on PROJ-456.</p>",
        date: new Date("2026-01-17T11:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_23",
        messageId: "msg_023",
        from: "newsletter@vercel.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Next.js 15 Released!",
        text: "We're excited to announce the release of Next.js 15 with new features.",
        html: "<h1>Next.js 15 Released!</h1><p>Explore the new features.</p>",
        date: new Date("2026-01-18T14:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_24",
        messageId: "msg_024",
        from: "subscriptions@spotify.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Wrapped 2025 is Ready!",
        text: "Discover your most listened to songs and artists of 2025.",
        html: "<h1>Spotify Wrapped 2025</h1><p>See your year in music!</p>",
        date: new Date("2026-01-19T08:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_25",
        messageId: "msg_025",
        from: "admin@cloudflare.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "DNS Records Updated Successfully",
        text: "Your DNS records for example.com have been updated.",
        html: "<h2>DNS Update</h2><p>Records for example.com updated successfully.</p>",
        date: new Date("2026-01-21T16:20:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_26",
        messageId: "msg_026",
        from: "recruitment@techcorp.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Interview Invitation: Senior Developer Position",
        text: "We'd like to invite you for an interview for the Senior Developer role.",
        html: "<h2>Interview Invitation</h2><p>Schedule your interview with us.</p>",
        date: new Date("2026-01-23T10:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_27",
        messageId: "msg_027",
        from: "noreply@docker.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Container Build Failed",
        text: "Your Docker image build for app-frontend:latest has failed.",
        html: "<h3>Build Failed</h3><p>Check the build logs for details.</p>",
        date: new Date("2026-01-24T13:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_28",
        messageId: "msg_028",
        from: "travel@booking.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Booking Confirmation #78945",
        text: "Your hotel reservation in Paris has been confirmed.",
        html: "<h2>Booking Confirmed</h2><p>Hotel in Paris, Feb 20-25.</p>",
        date: new Date("2026-01-26T09:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_29",
        messageId: "msg_029",
        from: "updates@notion.so",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Page Shared: Product Roadmap",
        text: "Sarah has shared the 'Product Roadmap' page with you.",
        html: "<h2>Page Shared</h2><p>Access the Product Roadmap page.</p>",
        date: new Date("2026-01-27T15:10:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_30",
        messageId: "msg_030",
        from: "alerts@datadog.com",
        to: [firstEmailAddress.email],
        cc: ["devops@company.com"],
        bcc: [],
        subject: "Alert: High CPU Usage Detected",
        text: "CPU usage on production-server-01 has exceeded 90%.",
        html: "<h2>Alert: High CPU Usage</h2><p>Immediate attention required.</p>",
        date: new Date("2026-01-29T18:20:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_31",
        messageId: "msg_031",
        from: "education@udemy.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Course Sale: 80% Off All Courses",
        text: "Limited time offer: Get 80% off all courses on Udemy.",
        html: "<h1>Course Sale</h1><p>80% off all courses - ends soon!</p>",
        date: new Date("2026-01-30T07:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_32",
        messageId: "msg_032",
        from: "info@stripe.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Payout Scheduled: $1,250.00",
        text: "Your payout of $1,250.00 will arrive in 2 business days.",
        html: "<h2>Payout Scheduled</h2><p>$1,250.00 arriving soon.</p>",
        date: new Date("2026-01-31T12:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_33",
        messageId: "msg_033",
        from: "team@asana.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Task Assigned: Update Documentation",
        text: "You've been assigned a new task: Update Documentation.",
        html: "<h3>Task Assigned</h3><p>Update Documentation - Due Feb 10.</p>",
        date: new Date("2026-02-01T10:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_34",
        messageId: "msg_034",
        from: "newsletter@css-tricks.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Modern CSS Techniques You Should Know",
        text: "Explore the latest CSS techniques for modern web development.",
        html: "<h1>Modern CSS</h1><p>Learn the latest techniques.</p>",
        date: new Date("2026-02-02T08:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_35",
        messageId: "msg_035",
        from: "help@railway.app",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Deployment Successful: Production",
        text: "Your application has been deployed successfully to production.",
        html: "<h2>Deployment Successful</h2><p>Your app is live!</p>",
        date: new Date("2026-02-02T14:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_36",
        messageId: "msg_036",
        from: "news@techcrunch.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Daily Crunch: AI Startup Raises $100M",
        text: "Today's top story: New AI startup raises $100M in Series B.",
        html: "<h1>Daily Crunch</h1><p>AI startup raises $100M.</p>",
        date: new Date("2026-02-03T06:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_37",
        messageId: "msg_037",
        from: "security@1password.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Password Breach Alert",
        text: "One of your saved passwords was found in a data breach.",
        html: "<h2>Security Alert</h2><p>Change your password immediately.</p>",
        date: new Date("2026-02-03T11:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_38",
        messageId: "msg_038",
        from: "community@dev.to",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Post Got Featured!",
        text: "Congratulations! Your article has been featured on the homepage.",
        html: "<h1>Post Featured!</h1><p>Your article is on the homepage.</p>",
        date: new Date("2026-02-04T09:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_39",
        messageId: "msg_039",
        from: "reports@analytics.google.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Weekly Analytics Report",
        text: "Your website had 15,000 visitors last week, up 25%.",
        html: "<h2>Weekly Analytics</h2><p>15K visitors, +25% growth!</p>",
        date: new Date("2026-02-04T16:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_40",
        messageId: "msg_040",
        from: "notifications@gitlab.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Pipeline Failed: feature/authentication",
        text: "CI/CD pipeline for feature/authentication branch has failed.",
        html: "<h3>Pipeline Failed</h3><p>Check the pipeline logs.</p>",
        date: new Date("2026-02-05T07:20:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_41",
        messageId: "msg_041",
        from: "deals@humblebundle.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Bundle: Developer Tools",
        text: "Check out our new developer tools bundle with huge savings.",
        html: "<h1>New Bundle</h1><p>Developer tools at great prices!</p>",
        date: new Date("2026-02-05T12:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_42",
        messageId: "msg_042",
        from: "receipts@uber.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Ride Receipt: $25.50",
        text: "Thank you for riding with Uber. Your trip cost $25.50.",
        html: "<h2>Ride Receipt</h2><p>Trip cost: $25.50</p>",
        date: new Date("2026-02-05T18:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_43",
        messageId: "msg_043",
        from: "legal@company.com",
        to: [firstEmailAddress.email],
        cc: ["compliance@company.com"],
        bcc: [],
        subject: "Updated Terms of Service",
        text: "We've updated our Terms of Service. Please review the changes.",
        html: "<h2>Terms of Service Update</h2><p>Review the changes.</p>",
        date: new Date("2026-02-06T08:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_44",
        messageId: "msg_044",
        from: "updates@trello.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Card Moved: Bug Fix - Critical",
        text: "The card 'Bug Fix - Critical' was moved to 'In Progress'.",
        html: "<h3>Card Moved</h3><p>Bug Fix moved to In Progress.</p>",
        date: new Date("2026-02-06T10:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_45",
        messageId: "msg_045",
        from: "subscriptions@netflix.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Season Available: Your Favorite Show",
        text: "Season 4 of your favorite show is now available to watch!",
        html: "<h1>New Season!</h1><p>Season 4 now streaming.</p>",
        date: new Date("2026-02-06T15:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_46",
        messageId: "msg_046",
        from: "system@jenkins.io",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Build Success: main-branch #234",
        text: "Build #234 on main-branch completed successfully.",
        html: "<h2>Build Success</h2><p>Build #234 completed.</p>",
        date: new Date("2026-02-07T06:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_47",
        messageId: "msg_047",
        from: "invitations@zoom.us",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Meeting Invitation: Client Presentation",
        text: "You're invited to a Zoom meeting: Client Presentation on Feb 10.",
        html: "<h2>Meeting Invitation</h2><p>Client Presentation - Feb 10.</p>",
        date: new Date("2026-02-07T09:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_48",
        messageId: "msg_048",
        from: "digest@hackernews.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "HN Digest: Top 10 Stories Today",
        text: "Here are today's top 10 stories from Hacker News.",
        html: "<h1>HN Digest</h1><p>Today's top 10 stories.</p>",
        date: new Date("2026-02-07T12:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_49",
        messageId: "msg_049",
        from: "feedback@app.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "We'd Love Your Feedback!",
        text: "Help us improve by taking a 2-minute survey about your experience.",
        html: "<h2>Feedback Request</h2><p>Take our 2-minute survey.</p>",
        date: new Date("2026-02-07T15:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_50",
        messageId: "msg_050",
        from: "monitoring@sentry.io",
        to: [firstEmailAddress.email],
        cc: ["developers@company.com"],
        bcc: [],
        subject: "Error Rate Spike Detected",
        text: "Your application error rate has increased by 300% in the last hour.",
        html: "<h2>Error Rate Spike</h2><p>Investigate immediately!</p>",
        date: new Date("2026-02-07T16:45:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_51",
        messageId: "msg_051",
        from: "shop@etsy.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Order is Being Prepared",
        text: "The seller is preparing your order #ETY789456.",
        html: "<h2>Order Update</h2><p>Your order is being prepared.</p>",
        date: new Date("2026-01-14T11:20:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_52",
        messageId: "msg_052",
        from: "alerts@pingdom.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Website Down: example.com",
        text: "Your website example.com is currently unreachable.",
        html: "<h2>Website Down</h2><p>example.com is unreachable!</p>",
        date: new Date("2026-01-16T03:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_53",
        messageId: "msg_053",
        from: "courses@coursera.org",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Certificate Earned: Machine Learning",
        text: "Congratulations! You've earned a certificate in Machine Learning.",
        html: "<h1>Certificate Earned!</h1><p>Machine Learning certificate.</p>",
        date: new Date("2026-01-17T14:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_54",
        messageId: "msg_054",
        from: "support@zendesk.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Ticket Closed: #12345",
        text: "Your support ticket #12345 has been resolved and closed.",
        html: "<h2>Ticket Closed</h2><p>Issue #12345 resolved.</p>",
        date: new Date("2026-01-18T16:30:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_55",
        messageId: "msg_055",
        from: "reviews@producthunt.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Your Product is Live on Product Hunt!",
        text: "Your product has been launched on Product Hunt. Good luck!",
        html: "<h1>Product Live!</h1><p>Now live on Product Hunt.</p>",
        date: new Date("2026-01-19T06:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_56",
        messageId: "msg_056",
        from: "notifications@discord.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "New Message in #general",
        text: "You have 25 new messages in the #general channel.",
        html: "<h3>New Messages</h3><p>25 messages in #general.</p>",
        date: new Date("2026-01-20T19:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_57",
        messageId: "msg_057",
        from: "invoices@freshbooks.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Invoice #INV-789 Paid",
        text: "Invoice #INV-789 for $850.00 has been paid by the client.",
        html: "<h2>Invoice Paid</h2><p>$850.00 received.</p>",
        date: new Date("2026-01-21T10:15:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_58",
        messageId: "msg_058",
        from: "tips@vscode.dev",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "VS Code Tip: Multiple Cursors",
        text: "Learn how to use multiple cursors to boost your productivity.",
        html: "<h1>VS Code Tip</h1><p>Master multiple cursors.</p>",
        date: new Date("2026-01-22T13:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_59",
        messageId: "msg_059",
        from: "reminders@todoist.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Reminder: Complete Project Proposal",
        text: "Don't forget to complete your project proposal by tomorrow.",
        html: "<h2>Reminder</h2><p>Complete project proposal.</p>",
        date: new Date("2026-01-23T17:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
      {
        id: "email_60",
        messageId: "msg_060",
        from: "billing@twilio.com",
        to: [firstEmailAddress.email],
        cc: [],
        bcc: [],
        subject: "Monthly Usage Report: January 2026",
        text: "Your Twilio usage for January: 1,250 SMS sent, $37.50 total.",
        html: "<h2>Usage Report</h2><p>January usage: $37.50</p>",
        date: new Date("2026-01-24T08:00:00Z"),
        emailAddressId: firstEmailAddress.id,
      },
    ],
    skipDuplicates: true,
  });

  console.log("✅ Created 60 emails for", firstEmailAddress.email);
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
